version: '3.8'

services:
  SnowCLIP:
    image: snowclip:tim
    shm_size: 16gb # Set shared memory to 16 gigabyte
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: SnowCLIP
    volumes:
      #- /mnt/c/mappilary_street_level:/workspaces/SnowCLIP/mappilary_street_level
      #- /mnt/c/Users/Timothy/Downloads/GSW10k:/workspaces/SnowCLIP/GSW10k
      - ../:/workspaces/SnowCLIP
      - /mnt/c/Users/Timothy/Downloads/gsv-cities-2:/workspaces/SnowCLIP/gsv-cities
    ports:
      - "8888:8888" # Adjust the port mapping as needed
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Adjust GPU visibility as needed
    command: "/bin/bash -c 'source /etc/bash.bashrc && tail -f /dev/null && /bin/bash'" # Keep container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
